apiVersion: v1
kind: Service
metadata:
  name: my-angular-k8s-devops
spec:
  ports:
    - port: 80
  selector:
    app: my-angular-k8s-devops
---
apiVersion: v1
kind: Service
metadata:
  name: my-angular-k8s-devops
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: my-angular-k8s-devops
