# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mouinck8smyangularnginx

on:
  push:
    branches:
      - kubernetes
  workflow_dispatch:

  # Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: "mouincnodejs"
  CLUSTER_NAME: "angular"
  CLUSTER_RESOURCE_GROUP: "docker"
  NAMESPACE: "angular"
  SECRET: "mouincnodejs-secret"
  APP_NAME: "my-angular"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://mouincnodejs.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_dd5ac53e8e144e628dc4585185bdc415 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_44a62f72a8214b33bc4bd15cc1d70f36 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mouincnodejs.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dd5ac53e8e144e628dc4585185bdc415 }}/k8s-myangular-nginx:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Login to registry
      - name: Log in to registry
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Set the target Azure Kubernetes Service (AKS) cluster.
      - name: Set the target Azure Kubernetes Service cluster.
        uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      # - name: Log in to registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: https://mouincnodejs.azurecr.io/
      #     username: ${{ secrets.AzureAppService_ContainerUsername_dd5ac53e8e144e628dc4585185bdc415 }}
      #     password: ${{ secrets.AzureAppService_ContainerPassword_44a62f72a8214b33bc4bd15cc1d70f36 }}

      # # Set the target Azure Kubernetes Service (AKS) cluster.
      # - uses: azure/aks-set-context@v1
      #   with:
      #     creds: "${{ secrets.AZURE_CREDENTIALS }}"
      #     cluster-name: ${{ env.CLUSTER_NAME }}
      #     resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      # Create image pull secret for ACR
      - uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
          container-registry-username: ${{ secrets.AzureAppService_ContainerUsername_dd5ac53e8e144e628dc4585185bdc415 }}
          container-registry-password: ${{ secrets.AzureAppService_ContainerPassword_44a62f72a8214b33bc4bd15cc1d70f36 }}
          secret-name: ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
          arguments: --force true

      # Deploy app to AKS
      - name: Deploy app to AKS
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ${{ github.workspace }}/manifests/deployment.yaml
            ${{ github.workspace }}/manifests/service.yaml
          images: |
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
